package com.clinica.config;

import org.hibernate.dialect.PostgreSQLDialect;
import org.hibernate.dialect.identity.IdentityColumnSupport;
import org.hibernate.dialect.identity.IdentityColumnSupportImpl;

/**
 * Custom PostgreSQL dialect that uses GENERATED ALWAYS AS IDENTITY
 * instead of the default GENERATED BY DEFAULT AS IDENTITY.
 * <p>
 * This is the modern PostgreSQL standard for identity columns,
 * ensuring IDs are always system-generated.
 * <p>
 * Hibernate with GenerationType.IDENTITY does not include the
 * identity column in INSERT statements, so OVERRIDING SYSTEM VALUE
 * is not needed for normal operations.
 */
public class CustomPostgreSQLDialect extends PostgreSQLDialect {

    private static final IdentityColumnSupport IDENTITY_COLUMN_SUPPORT =
        new IdentityColumnSupportImpl() {
            @Override
            public String getIdentityColumnString(int type) {
                return "generated always as identity";
            }
        };

    @Override
    public IdentityColumnSupport getIdentityColumnSupport() {
        return IDENTITY_COLUMN_SUPPORT;
    }
}
