-- ============================================================
-- V37: Entidad - Empresa + SUNAT consulta log tables
-- ============================================================

-- ============================================================
-- Table: entidad_empresa
-- Legal entities (RUC 10 / RUC 20) for Factura clients and suppliers.
-- ============================================================
CREATE TABLE entidad_empresa (
    emp_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_ruc             VARCHAR(11) NOT NULL,
    emp_tipo_ruc        VARCHAR(10) NOT NULL,
    emp_razon_social    VARCHAR(255),
    emp_direccion_fiscal VARCHAR(255),
    emp_ubigeo          VARCHAR(6),
    emp_telefono        VARCHAR(20),
    emp_email           VARCHAR(100),
    emp_estado          VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
    emp_rol             VARCHAR(15) NOT NULL DEFAULT 'CLIENTE',
    emp_persona_id      BIGINT,
    emp_created_at      TIMESTAMP NOT NULL,
    emp_updated_at      TIMESTAMP,
    emp_activo          BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_emp_ruc UNIQUE (emp_ruc),
    CONSTRAINT fk_emp_persona FOREIGN KEY (emp_persona_id)
        REFERENCES tb_personas(pers_persona_id),
    CONSTRAINT chk_emp_tipo_ruc CHECK (emp_tipo_ruc IN ('RUC_10', 'RUC_20')),
    CONSTRAINT chk_emp_estado CHECK (emp_estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT chk_emp_rol CHECK (emp_rol IN ('CLIENTE', 'PROVEEDOR', 'AMBOS'))
);

CREATE INDEX idx_emp_ruc ON entidad_empresa(emp_ruc);
CREATE INDEX idx_emp_razon_social ON entidad_empresa(emp_razon_social);
CREATE INDEX idx_emp_estado ON entidad_empresa(emp_estado);
CREATE INDEX idx_emp_rol ON entidad_empresa(emp_rol);

COMMENT ON TABLE entidad_empresa IS 'Legal entities for Factura clients and suppliers';
COMMENT ON COLUMN entidad_empresa.emp_ruc IS 'RUC number (11 digits), validated with modulo 11';
COMMENT ON COLUMN entidad_empresa.emp_tipo_ruc IS 'RUC_10 (persona natural) or RUC_20 (persona juridica)';
COMMENT ON COLUMN entidad_empresa.emp_rol IS 'CLIENTE, PROVEEDOR, or AMBOS - auto-promoted by context';
COMMENT ON COLUMN entidad_empresa.emp_persona_id IS 'FK to Persona when RUC 10 matches an existing person';

-- ============================================================
-- Table: entidad_sunat_consulta_log
-- Audit log for all SUNAT RUC API queries.
-- ============================================================
CREATE TABLE entidad_sunat_consulta_log (
    sun_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sun_ruc             VARCHAR(11) NOT NULL,
    sun_fecha           TIMESTAMP NOT NULL,
    sun_ip_origen       VARCHAR(45),
    sun_usuario_id      BIGINT,
    sun_respuesta_raw   VARCHAR(2000),
    sun_exito           BOOLEAN NOT NULL,
    sun_created_at      TIMESTAMP NOT NULL,
    sun_updated_at      TIMESTAMP,
    sun_activo          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_sun_ruc ON entidad_sunat_consulta_log(sun_ruc);
CREATE INDEX idx_sun_fecha ON entidad_sunat_consulta_log(sun_fecha);

COMMENT ON TABLE entidad_sunat_consulta_log IS 'Audit log for SUNAT RUC API queries';
COMMENT ON COLUMN entidad_sunat_consulta_log.sun_respuesta_raw IS 'Raw API response (may contain PII - excluded from logs)';
