-- ============================================================
-- V38: Caja - Tarifario + Paquete tables
-- ============================================================

-- ============================================================
-- Table: caja_tarifario
-- Tariff schedule (one per aseguradora; NULL = particular).
-- ============================================================
CREATE TABLE caja_tarifario (
    tar_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tar_nombre          VARCHAR(100) NOT NULL,
    tar_descripcion     VARCHAR(255),
    tar_aseguradora_id  BIGINT,
    tar_created_at      TIMESTAMP NOT NULL,
    tar_updated_at      TIMESTAMP,
    tar_activo          BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE caja_tarifario IS 'Tariff schedule: one per aseguradora (NULL = particular/self-pay)';

-- ============================================================
-- Table: caja_tarifario_item
-- Individual pricing items within a tarifario with temporal validity.
-- Price changes create new rows (never mutate).
-- ============================================================
CREATE TABLE caja_tarifario_item (
    tait_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tait_tarifario_id   BIGINT NOT NULL,
    tait_codigo         VARCHAR(50) NOT NULL,
    tait_nombre         VARCHAR(200) NOT NULL,
    tait_descripcion    VARCHAR(500),
    tait_precio_base    DECIMAL(10,2) NOT NULL,
    tait_precio_final   DECIMAL(10,2) NOT NULL,
    tait_unidad_medida_id INTEGER,
    tait_fecha_desde    DATE NOT NULL,
    tait_fecha_hasta    DATE,
    tait_created_at     TIMESTAMP NOT NULL,
    tait_updated_at     TIMESTAMP,
    tait_activo         BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_tait_tarifario FOREIGN KEY (tait_tarifario_id)
        REFERENCES caja_tarifario(tar_id),
    CONSTRAINT uq_tait_codigo_desde UNIQUE (tait_codigo, tait_fecha_desde)
);

CREATE INDEX idx_tait_codigo ON caja_tarifario_item(tait_codigo);
CREATE INDEX idx_tait_fecha_desde ON caja_tarifario_item(tait_fecha_desde);
CREATE INDEX idx_tait_fecha_hasta ON caja_tarifario_item(tait_fecha_hasta);
CREATE INDEX idx_tait_tarifario_id ON caja_tarifario_item(tait_tarifario_id);

COMMENT ON TABLE caja_tarifario_item IS 'Individual prices with temporal validity; new rows on price change';
COMMENT ON COLUMN caja_tarifario_item.tait_precio_base IS 'Base cost before markup (IGV + utilidad)';
COMMENT ON COLUMN caja_tarifario_item.tait_precio_final IS 'Cached final price = base + IGV + utilidad';
COMMENT ON COLUMN caja_tarifario_item.tait_fecha_hasta IS 'NULL = currently active price';

-- ============================================================
-- Table: caja_paquete
-- Predefined bundles of prestaciones with a single price.
-- ============================================================
CREATE TABLE caja_paquete (
    paq_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paq_codigo          VARCHAR(50) NOT NULL,
    paq_nombre          VARCHAR(200) NOT NULL,
    paq_descripcion     VARCHAR(500),
    paq_precio_total    DECIMAL(10,2) NOT NULL,
    paq_created_at      TIMESTAMP NOT NULL,
    paq_updated_at      TIMESTAMP,
    paq_activo          BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_paq_codigo UNIQUE (paq_codigo)
);

CREATE INDEX idx_paq_codigo ON caja_paquete(paq_codigo);

COMMENT ON TABLE caja_paquete IS 'Predefined service bundles with bundled price';

-- ============================================================
-- Table: caja_paquete_detalle
-- Items within a package, referencing tarifario items.
-- ============================================================
CREATE TABLE caja_paquete_detalle (
    pad_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pad_paquete_id      BIGINT NOT NULL,
    pad_tarifario_item_id BIGINT NOT NULL,
    pad_cantidad        INTEGER NOT NULL DEFAULT 1,
    pad_created_at      TIMESTAMP NOT NULL,
    pad_updated_at      TIMESTAMP,
    pad_activo          BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_pad_paquete FOREIGN KEY (pad_paquete_id)
        REFERENCES caja_paquete(paq_id),
    CONSTRAINT fk_pad_tarifario_item FOREIGN KEY (pad_tarifario_item_id)
        REFERENCES caja_tarifario_item(tait_id)
);

CREATE INDEX idx_pad_paquete_id ON caja_paquete_detalle(pad_paquete_id);

COMMENT ON TABLE caja_paquete_detalle IS 'Items within a package referencing tarifario items';
