-- ============================================================
-- V39: Caja - SesionCaja + TipoCambio tables
-- ============================================================

-- ============================================================
-- Table: caja_sesion_caja
-- Cash register session tracking: open/close, discrepancy.
-- Independent from farmacia caja sessions (Series 004).
-- ============================================================
CREATE TABLE caja_sesion_caja (
    ses_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ses_codigo              VARCHAR(50) NOT NULL,
    ses_usuario_apertura_id BIGINT NOT NULL,
    ses_fecha_apertura      TIMESTAMP NOT NULL,
    ses_monto_apertura      DECIMAL(10,2) NOT NULL,
    ses_estado              VARCHAR(20) NOT NULL DEFAULT 'ABIERTA',
    ses_usuario_cierre_id   BIGINT,
    ses_fecha_cierre        TIMESTAMP,
    ses_monto_cierre        DECIMAL(10,2),
    ses_total_ventas        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ses_diferencia          DECIMAL(10,2),
    ses_observaciones       VARCHAR(500),
    ses_created_at          TIMESTAMP NOT NULL,
    ses_updated_at          TIMESTAMP,
    ses_activo              BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_ses_codigo UNIQUE (ses_codigo)
);

CREATE INDEX idx_ses_usuario_apertura ON caja_sesion_caja(ses_usuario_apertura_id);
CREATE INDEX idx_ses_estado ON caja_sesion_caja(ses_estado);
CREATE INDEX idx_ses_fecha_apertura ON caja_sesion_caja(ses_fecha_apertura);

COMMENT ON TABLE caja_sesion_caja IS 'Cash register session: tracks open/close amounts and discrepancy';
COMMENT ON COLUMN caja_sesion_caja.ses_codigo IS 'Unique session code (e.g. SES-20260612-0001)';
COMMENT ON COLUMN caja_sesion_caja.ses_usuario_apertura_id IS 'Cashier who opened the session';
COMMENT ON COLUMN caja_sesion_caja.ses_monto_apertura IS 'Initial cash amount in drawer';
COMMENT ON COLUMN caja_sesion_caja.ses_total_ventas IS 'Sum of all liquidacion amounts in this session';
COMMENT ON COLUMN caja_sesion_caja.ses_diferencia IS 'ses_monto_cierre - ses_monto_apertura - ses_total_ventas';
COMMENT ON COLUMN caja_sesion_caja.ses_observaciones IS 'Free-text notes (e.g. discrepancy reason)';

-- ============================================================
-- Table: caja_tipo_cambio
-- Per-transaction foreign exchange rate records.
-- ============================================================
CREATE TABLE caja_tipo_cambio (
    tcam_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tcam_moneda_origen  VARCHAR(3) NOT NULL,
    tcam_moneda_destino VARCHAR(3) NOT NULL,
    tcam_tipo_cambio    DECIMAL(10,4) NOT NULL,
    tcam_fecha          DATE NOT NULL,
    tcam_usuario_id     BIGINT NOT NULL,
    tcam_created_at     TIMESTAMP NOT NULL,
    tcam_updated_at     TIMESTAMP,
    tcam_activo         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_tcam_fecha ON caja_tipo_cambio(tcam_fecha);
CREATE INDEX idx_tcam_monedas ON caja_tipo_cambio(tcam_moneda_origen, tcam_moneda_destino);

COMMENT ON TABLE caja_tipo_cambio IS 'Exchange rate records per transaction date';
COMMENT ON COLUMN caja_tipo_cambio.tcam_moneda_origen IS 'Source currency code (e.g. USD)';
COMMENT ON COLUMN caja_tipo_cambio.tcam_moneda_destino IS 'Target currency code (e.g. PEN)';
COMMENT ON COLUMN caja_tipo_cambio.tcam_tipo_cambio IS 'Exchange rate (4 decimal places)';
