-- ============================================================
-- V40: Caja - Liquidacion + PaymentLeg tables
-- Billing and payment collection for clinical cashier.
-- ============================================================

-- ============================================================
-- Table: caja_liquidacion
-- Payment transaction record. Created when a cashier processes
-- payment for a Cuenta that is PENDIENTE_COBRO.
-- ============================================================
CREATE TABLE caja_liquidacion (
    liq_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    liq_cuenta_id         BIGINT NOT NULL,
    liq_sesion_id         BIGINT NOT NULL,
    liq_fecha             TIMESTAMP NOT NULL,
    liq_moneda            VARCHAR(3) NOT NULL DEFAULT 'PEN',
    liq_monto_total       DECIMAL(10,2) NOT NULL,
    liq_monto_usd         DECIMAL(10,2),
    liq_monto_pen         DECIMAL(10,2),
    liq_tipo_cambio_id    BIGINT,
    liq_descuento_total   DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    liq_descuento_porcentaje DECIMAL(5,2),
    liq_usuario_aprueba_id BIGINT,
    liq_fecha_aprobacion  TIMESTAMP,
    liq_usuario_cobra_id  BIGINT NOT NULL,
    liq_estado            VARCHAR(20) NOT NULL DEFAULT 'PAGADO',
    liq_created_at        TIMESTAMP NOT NULL,
    liq_updated_at        TIMESTAMP,
    liq_activo            BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_liq_tipo_cambio FOREIGN KEY (liq_tipo_cambio_id) REFERENCES caja_tipo_cambio(tcam_id)
);

CREATE INDEX idx_liq_cuenta ON caja_liquidacion(liq_cuenta_id);
CREATE INDEX idx_liq_sesion ON caja_liquidacion(liq_sesion_id);
CREATE INDEX idx_liq_fecha ON caja_liquidacion(liq_fecha);
CREATE INDEX idx_liq_estado ON caja_liquidacion(liq_estado);

COMMENT ON TABLE caja_liquidacion IS 'Payment transaction record for a Cuenta';
COMMENT ON COLUMN caja_liquidacion.liq_cuenta_id IS 'Reference to clinica Cuenta (no FK — cross-module)';
COMMENT ON COLUMN caja_liquidacion.liq_sesion_id IS 'Reference to the open SesionCaja when payment was processed';
COMMENT ON COLUMN caja_liquidacion.liq_moneda IS 'Transaction currency: PEN or USD';
COMMENT ON COLUMN caja_liquidacion.liq_monto_total IS 'Total amount in transaction currency';
COMMENT ON COLUMN caja_liquidacion.liq_monto_usd IS 'USD amount when moneda=USD; null when moneda=PEN';
COMMENT ON COLUMN caja_liquidacion.liq_monto_pen IS 'PEN amount; equals monto_total when moneda=PEN, converted when moneda=USD';
COMMENT ON COLUMN caja_liquidacion.liq_tipo_cambio_id IS 'Exchange rate record for USD transactions';
COMMENT ON COLUMN caja_liquidacion.liq_descuento_total IS 'Total discount applied (monetary)';
COMMENT ON COLUMN caja_liquidacion.liq_descuento_porcentaje IS 'Discount percentage (for audit)';
COMMENT ON COLUMN caja_liquidacion.liq_usuario_aprueba_id IS 'User who approved the discount (Gerencia/Admin)';
COMMENT ON COLUMN caja_liquidacion.liq_fecha_aprobacion IS 'When the discount was approved';
COMMENT ON COLUMN caja_liquidacion.liq_usuario_cobra_id IS 'Cashier who processed the payment';
COMMENT ON COLUMN caja_liquidacion.liq_estado IS 'Payment state: PAGADO';

-- ============================================================
-- Table: caja_payment_leg
-- Individual payment leg within a liquidacion.
-- Supports split payments across multiple methods.
-- ============================================================
CREATE TABLE caja_payment_leg (
    pag_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pag_liquidacion_id    BIGINT NOT NULL,
    pag_metodo_pago       VARCHAR(30) NOT NULL,
    pag_monto             DECIMAL(10,2) NOT NULL,
    pag_referencia        VARCHAR(100),
    pag_created_at        TIMESTAMP NOT NULL,
    pag_updated_at        TIMESTAMP,
    pag_activo            BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_pag_liquidacion FOREIGN KEY (pag_liquidacion_id) REFERENCES caja_liquidacion(liq_id)
);

CREATE INDEX idx_pag_liquidacion ON caja_payment_leg(pag_liquidacion_id);

COMMENT ON TABLE caja_payment_leg IS 'Individual payment method leg within a liquidacion';
COMMENT ON COLUMN caja_payment_leg.pag_metodo_pago IS 'Payment method: EFECTIVO, POS, YAPE_PLIN, TRANSFERENCIA';
COMMENT ON COLUMN caja_payment_leg.pag_monto IS 'Amount paid with this method';
COMMENT ON COLUMN caja_payment_leg.pag_referencia IS 'Voucher/transaction ID; required for POS/YAPE_PLIN/TRANSFERENCIA';
