-- ============================================================
-- V41: Caja - Comprobante + ReprintLog tables
-- SUNAT-compliant electronic invoice management for clinical
-- cashier. Stores XML as CLOB, supports reprint audit trail.
-- ============================================================

-- ============================================================
-- Table: caja_comprobante
-- SUNAT electronic invoice record. Stores denormalized client
-- data at issuance time for XML immutability.
-- ============================================================
CREATE TABLE caja_comprobante (
    com_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    com_tipo_comprobante_id INTEGER NOT NULL,
    com_serie               VARCHAR(4) NOT NULL DEFAULT '001',
    com_correlativo         VARCHAR(8) NOT NULL,
    com_fecha_emision       TIMESTAMP NOT NULL,
    com_tipo_doc_cliente    VARCHAR(2) NOT NULL,
    com_num_doc_cliente     VARCHAR(20) NOT NULL,
    com_nombre_cliente      VARCHAR(255) NOT NULL,
    com_direccion_cliente   VARCHAR(255),
    com_persona_id          BIGINT,
    com_empresa_id          BIGINT,
    com_subtotal            DECIMAL(10,2) NOT NULL,
    com_igv                 DECIMAL(10,2) NOT NULL,
    com_total               DECIMAL(10,2) NOT NULL,
    com_moneda              VARCHAR(3) NOT NULL DEFAULT 'PEN',
    com_liquidacion_id      BIGINT,
    com_xml_generado        TEXT,
    com_estado              VARCHAR(20) NOT NULL DEFAULT 'EMITIDO',
    com_comprobante_original_id BIGINT,
    com_motivo              VARCHAR(500),
    com_created_at          TIMESTAMP NOT NULL,
    com_updated_at          TIMESTAMP,
    com_activo              BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_com_tipo_comprobante FOREIGN KEY (com_tipo_comprobante_id)
        REFERENCES tb_tipos_comprobante(tcomp_id),
    CONSTRAINT fk_com_comprobante_original FOREIGN KEY (com_comprobante_original_id)
        REFERENCES caja_comprobante(com_id),
    CONSTRAINT uq_com_serie_correlativo UNIQUE (com_serie, com_correlativo)
);

CREATE INDEX idx_com_liquidacion ON caja_comprobante(com_liquidacion_id);
CREATE INDEX idx_com_persona ON caja_comprobante(com_persona_id);
CREATE INDEX idx_com_empresa ON caja_comprobante(com_empresa_id);
CREATE INDEX idx_com_estado ON caja_comprobante(com_estado);
CREATE INDEX idx_com_fecha ON caja_comprobante(com_fecha_emision);
CREATE INDEX idx_com_serie_correlativo ON caja_comprobante(com_serie, com_correlativo);

COMMENT ON TABLE caja_comprobante IS 'SUNAT-compliant electronic invoice/comprobante record';
COMMENT ON COLUMN caja_comprobante.com_tipo_comprobante_id IS 'FK to tb_tipos_comprobante: 01=Factura, 03=Boleta, 07=NotaCredito';
COMMENT ON COLUMN caja_comprobante.com_serie IS 'Series: 001 for Caja Clinica, 004 for Farmacia';
COMMENT ON COLUMN caja_comprobante.com_correlativo IS 'Auto-increment 8-digit number within series';
COMMENT ON COLUMN caja_comprobante.com_fecha_emision IS 'When the comprobante was issued';
COMMENT ON COLUMN caja_comprobante.com_tipo_doc_cliente IS 'SUNAT doc type: 1=DNI, 6=RUC, etc.';
COMMENT ON COLUMN caja_comprobante.com_num_doc_cliente IS 'Client document number (denormalized)';
COMMENT ON COLUMN caja_comprobante.com_nombre_cliente IS 'Client name/razon social (denormalized)';
COMMENT ON COLUMN caja_comprobante.com_direccion_cliente IS 'Client address (denormalized)';
COMMENT ON COLUMN caja_comprobante.com_persona_id IS 'Persona reference for Boleta (nullable if Factura)';
COMMENT ON COLUMN caja_comprobante.com_empresa_id IS 'Empresa reference for Factura (nullable if Boleta)';
COMMENT ON COLUMN caja_comprobante.com_subtotal IS 'Subtotal before IGV';
COMMENT ON COLUMN caja_comprobante.com_igv IS 'IGV 18% amount';
COMMENT ON COLUMN caja_comprobante.com_total IS 'Total including IGV';
COMMENT ON COLUMN caja_comprobante.com_moneda IS 'Currency: PEN or USD';
COMMENT ON COLUMN caja_comprobante.com_liquidacion_id IS 'Reference to the payment liquidacion';
COMMENT ON COLUMN caja_comprobante.com_xml_generado IS 'SUNAT UBL 2.1 XML content (CLOB) — PII data, excluded from logs';
COMMENT ON COLUMN caja_comprobante.com_estado IS 'Estado: EMITIDO or ANULADO';
COMMENT ON COLUMN caja_comprobante.com_comprobante_original_id IS 'Self-ref FK: original comprobante for Nota Credito';
COMMENT ON COLUMN caja_comprobante.com_motivo IS 'Motivo for Nota Credito or cancellation';

-- ============================================================
-- Table: caja_reprint_log
-- Audit trail for all comprobante reprint actions.
-- ============================================================
CREATE TABLE caja_reprint_log (
    rep_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rep_comprobante_id  BIGINT NOT NULL,
    rep_usuario_id      BIGINT NOT NULL,
    rep_fecha           TIMESTAMP NOT NULL,
    rep_ip_origen       VARCHAR(45),
    rep_created_at      TIMESTAMP NOT NULL,
    rep_updated_at      TIMESTAMP,
    rep_activo          BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_rep_comprobante FOREIGN KEY (rep_comprobante_id)
        REFERENCES caja_comprobante(com_id)
);

CREATE INDEX idx_rep_comprobante ON caja_reprint_log(rep_comprobante_id);
CREATE INDEX idx_rep_fecha ON caja_reprint_log(rep_fecha);

COMMENT ON TABLE caja_reprint_log IS 'Audit log for comprobante reprint actions';
COMMENT ON COLUMN caja_reprint_log.rep_comprobante_id IS 'Comprobante that was reprinted';
COMMENT ON COLUMN caja_reprint_log.rep_usuario_id IS 'User who performed the reprint';
COMMENT ON COLUMN caja_reprint_log.rep_fecha IS 'When the reprint occurred';
COMMENT ON COLUMN caja_reprint_log.rep_ip_origen IS 'IP address of the requesting client';
